@echo off
echo Cleaning up any existing processes...
taskkill /F /IM node.exe /T > nul 2>&1
timeout /t 2 /nobreak > nul
echo Starting server and client for E2E tests...
start /B npm run dev
echo Waiting for server and client to be ready...
timeout /t 25 /nobreak > nul
echo Running status change tests...
npm test -- tests/e2e/admin-status-change.test.js
echo Stopping server and client...
taskkill /F /IM node.exe /T > nul 2>&1
echo Test completed.