// Error Code Constants for Server-side Result Object Pattern
// These constants standardize error codes across the server application

// Main error codes object
const ERROR_CODES = {
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_OPERATION: 'INVALID_OPERATION',
  
  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  STATE_MISMATCH: 'STATE_MISMATCH',
  
  // Permission errors
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // System errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  EMAIL_ERROR: 'EMAIL_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  
  // Business logic errors
  DEPENDENCY_ERROR: 'DEPENDENCY_ERROR',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  
  // Service-specific errors
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  SERVICE_OVERLOADED: 'SERVICE_OVERLOADED',
  
  // File operation errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  FILE_PROCESSING_FAILED: 'FILE_PROCESSING_FAILED',
  
  // Data integrity errors
  DATA_CORRUPTION: 'DATA_CORRUPTION',
  DATA_INCONSISTENCY: 'DATA_INCONSISTENCY',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',
  
  // Configuration errors
  MISSING_CONFIGURATION: 'MISSING_CONFIGURATION',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  CONFIGURATION_MIGRATION_FAILED: 'CONFIGURATION_MIGRATION_FAILED'
};

module.exports = { ERROR_CODES };