name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.UNLICENSEDDRIVINGSCHOOLIP }}
          username: ${{ secrets.UNLICENSEDDRIVINGSCHOOL_USER }}
          key: ${{ secrets.UNLICENSEDDRIVERSSH }}
          script: |
            cd /var/www/unlicenseddrivingschoolsedschools
            git pull origin main
            npm install
            pm2 restart all 
