name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload built site to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.UNLICENSEDDRIVINGSCHOOLIP }}
          username: ${{ secrets.UNLICENSEDDRIVINGSCHOOL_USER }}
          key: ${{ secrets.UNLICENSEDDRIVERSSH }}
          source: "dist/*"
          target: "~/var/www/unlicenseddrivingschools/"

      - name: Restart Nginx (optional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UNLICENSEDDRIVINGSCHOOLIP }}
          username: ${{ secrets.UNLICENSEDDRIVINGSCHOOL_USER }}
          key: ${{ secrets.UNLICENSEDDRIVERSSH }}
          script: |
            sudo systemctl restart nginx
